version: '2'

services:
  mysql:
    image: 'bitnami/mysql:5:7'
    ports:
    - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password

